feat: Add generated NatSpec documentation (SC-10995)
maple-labs/maple-docs pull request #23
Opened 2023-01-18 20:04 UTC by vbidin

2023-01-19 19:57 UTC, JGcarv commented
Can you provide a simple overview on how we can generate this docs, please?

Also, there's conflicts on the PR

2023-01-26 16:19 UTC, deluca-mike requested changes

2023-01-26 16:19 UTC, deluca-mike commented on SUMMARY.md
> +  * [WithdrawalManagerInitializer](technical-resources/natspec/withdrawal-manager-initializer.md)
```suggestion
* Interfaces
  * [Liquidator](technical-resources/interfaces/liquidator.md)
  * [LiquidatorFactory](technical-resources/interfaces/liquidator-factory.md)
  * [LiquidatorInitializer](technical-resources/interfaces/liquidator-initializer.md)
  * [LoanManager](technical-resources/interfaces/loan-manager.md)
  * [LoanManagerFactory](technical-resources/interfaces/loan-manager-factory.md)
  * [LoanManagerInitializer](technical-resources/interfaces/loan-manager-initializer.md)
  * [MapleGlobals](technical-resources/interfaces/maple-globals.md)
  * [MapleLoan](technical-resources/interfaces/maple-loan.md)
  * [MapleLoanFactory](technical-resources/interfaces/maple-loan-factory.md)
  * [MapleLoanFeeManager](technical-resources/interfaces/maple-loan-fee-manager.md)
  * [MapleLoanInitializer](technical-resources/interfaces/maple-loan-initializer.md)
  * [Pool](technical-resources/interfaces/pool.md)
  * [PoolDelegateCover](technical-resources/interfaces/pool-delegate-cover.md)
  * [PoolManager](technical-resources/interfaces/pool-manager.md)
  * [PoolManagerFactory](technical-resources/interfaces/pool-manager-factory.md)
  * [PoolManagerInitializer](technical-resources/interfaces/pool-manager-initializer.md)
  * [Refinancer](technical-resources/interfaces/refinancer.md)
  * [WithdrawalManager](technical-resources/interfaces/withdrawal-manager.md)
  * [WithdrawalManagerFactory](technical-resources/interfaces/withdrawal-manager-factory.md)
  * [WithdrawalManagerInitializer](technical-resources/interfaces/withdrawal-manager-initializer.md)
```

2023-01-26 20:53 UTC, lucas-manuel commented on SUMMARY.md
> +  * [Liquidity Migration Procedure](technical-resources/operations/liquidity-migration-procedure.md)
Remove

2023-01-26 21:02 UTC, merged