feat: Update poolCreation section with deployPool function changes (SC-14966)
maple-labs/maple-docs pull request #92
Opened 2023-12-15 21:55 UTC by Preethisenthilkumar

2023-12-17 00:39 UTC, vbidin requested changes

2023-12-17 00:39 UTC, vbidin commented on technical-resources/pools/pool-creation.md
> +* `withdrawalManagerFactory` - The address of cyclical based withdrawal manager factory.
`Address of the cycle-based...`

2023-12-17 00:39 UTC, vbidin commented on technical-resources/pools/pool-creation.md
> +* `withdrawalManagerFactory` - The address of queue based withdrawal manager factory.
`Address of the queue-based...`

2023-12-18 18:31 UTC, JGcarv approved these changes

2023-12-19 09:21 UTC, 0xfarhaan approved these changes

2023-12-19 09:22 UTC, merged